/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ht22.QLDiemSinhVien.views.frames;

import com.ht22.QLDiemSinhVien.DAO.DAOKhoa;
import com.ht22.QLDiemSinhVien.entity.Khoa;
import com.ht22.QLDiemSinhVien.entity.Lop;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.List;

/**
 *
 * @author linht
 */
public class frm_khoa extends javax.swing.JFrame {
    private String tableValueSelected;

    DAOKhoa khoaDAO = new DAOKhoa();
    /**
     * Creates new form frm_khoa
     */
    public frm_khoa() {
        initComponents();
        initTable();
    }

    //    setModel Table
    public void setModelTable(List<Khoa> khoaList ){
        DefaultTableModel tableModel = new DefaultTableModel(
                new String[]{"Tên Khoa", "Mã Khoa"}, 0
        );

        for (Khoa khoa : khoaList) {
            // Thêm một hàng với các giá trị lấy từ đối tượng Lop
            tableModel.addRow(new Object[]{
                    khoa.getTenKhoa(),
                    khoa.getMaKhoa(),
            });
        }

        jTableKhoa.setModel(tableModel);
        jScrollPane1.setViewportView(jTableKhoa);
    }

    //    setTable
    public void initTable(){
//
        List<Khoa> khoaList = khoaDAO.getAll();
//        Set model data for Table
        setModelTable( khoaList );

//        handle click data on table
        jTableKhoa.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int selectedRow = jTableKhoa.getSelectedRow(); // Lấy chỉ số hàng được chọn

                if (selectedRow >= 0) { // Kiểm tra xem có hàng nào được chọn không

                    String maKhoa = jTableKhoa.getValueAt(selectedRow, 0).toString();
                    tableValueSelected = maKhoa;
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelKhoaAction = new javax.swing.JPanel();
        jPanelInputTenLop = new javax.swing.JPanel();
        jLabelInputTenKhoa = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPaneInputTenKhoa = new javax.swing.JTextPane();
        jButtonXoaKhoa = new javax.swing.JButton();
        jButtonThemKhoa = new javax.swing.JButton();
        jPanelInputMaLop = new javax.swing.JPanel();
        jLabelInputMaKhoa = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPaneInputMaKhoa = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKhoa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelInputTenKhoa.setText("Tên Khoa");

        jScrollPane3.setViewportView(jTextPaneInputTenKhoa);

        jButtonXoaKhoa.setText("Xóa Khoa");
        jButtonXoaKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaKhoaActionPerformed(evt);
            }
        });

        jButtonThemKhoa.setText("Thêm Khoa");
        jButtonThemKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemKhoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInputTenLopLayout = new javax.swing.GroupLayout(jPanelInputTenLop);
        jPanelInputTenLop.setLayout(jPanelInputTenLopLayout);
        jPanelInputTenLopLayout.setHorizontalGroup(
            jPanelInputTenLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInputTenLopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInputTenLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInputTenLopLayout.createSequentialGroup()
                        .addGroup(jPanelInputTenLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jLabelInputTenKhoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanelInputTenLopLayout.createSequentialGroup()
                        .addComponent(jButtonXoaKhoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonThemKhoa, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))))
        );
        jPanelInputTenLopLayout.setVerticalGroup(
            jPanelInputTenLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInputTenLopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInputTenKhoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInputTenLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonXoaKhoa)
                    .addComponent(jButtonThemKhoa))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabelInputMaKhoa.setText("Mã Khoa");

        jScrollPane4.setViewportView(jTextPaneInputMaKhoa);

        javax.swing.GroupLayout jPanelInputMaLopLayout = new javax.swing.GroupLayout(jPanelInputMaLop);
        jPanelInputMaLop.setLayout(jPanelInputMaLopLayout);
        jPanelInputMaLopLayout.setHorizontalGroup(
            jPanelInputMaLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInputMaLopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInputMaLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(jLabelInputMaKhoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelInputMaLopLayout.setVerticalGroup(
            jPanelInputMaLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInputMaLopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelInputMaKhoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanelKhoaActionLayout = new javax.swing.GroupLayout(jPanelKhoaAction);
        jPanelKhoaAction.setLayout(jPanelKhoaActionLayout);
        jPanelKhoaActionLayout.setHorizontalGroup(
            jPanelKhoaActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKhoaActionLayout.createSequentialGroup()
                .addComponent(jPanelInputTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInputMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelKhoaActionLayout.setVerticalGroup(
            jPanelKhoaActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInputTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelInputMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTableKhoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableKhoa);

        jLabel1.setText("Danh Sách Khoa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Back");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelKhoaAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelKhoaAction, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonXoaKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaKhoaActionPerformed
        // TODO add your handling code here:
        khoaDAO.delete(tableValueSelected);
        initTable();
    }//GEN-LAST:event_jButtonXoaKhoaActionPerformed

    private void jButtonThemKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemKhoaActionPerformed
        // TODO add your handling code here:

        String tenKhoa = jTextPaneInputTenKhoa.getText();
        String maKhoa = jTextPaneInputMaKhoa.getText();

        //  Create object from form input
        Khoa khoa = new Khoa(tenKhoa, maKhoa);

        try {
//            DAO insert
            khoaDAO.insert(khoa);
        } catch (SQLIntegrityConstraintViolationException e) {
            // Lỗi trùng khóa chính (hoặc unique key)
            JOptionPane.showMessageDialog(this, "Mã lớp đã tồn tại. Vui lòng nhập mã lớp khác.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            // Lỗi chung liên quan đến cơ sở dữ liệu
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi thêm dữ liệu: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Bắt các ngoại lệ khác nếu có
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi không xác định: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

        // Cập nhật lại bảng sau khi thêm thành công
        initTable();
    }//GEN-LAST:event_jButtonThemKhoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_khoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_khoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_khoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_khoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_khoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonThemKhoa;
    private javax.swing.JButton jButtonXoaKhoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelInputMaKhoa;
    private javax.swing.JLabel jLabelInputTenKhoa;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelInputMaLop;
    private javax.swing.JPanel jPanelInputTenLop;
    private javax.swing.JPanel jPanelKhoaAction;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableKhoa;
    private javax.swing.JTextPane jTextPaneInputMaKhoa;
    private javax.swing.JTextPane jTextPaneInputTenKhoa;
    // End of variables declaration//GEN-END:variables
}
